check:
  - thoth-precommit
  - thoth-build
build:
  build-stratergy: Dockerfile
  registry: quay.io
  registry-org: thoth-station
  registry-project: s2i-custom-notebook
  registry-secret: thoth-station-thoth-pusher-secret
